### ISSUE TITLE
Themes are missing in step 3.

### ISSUE THREAD

**Issue by aavrug** [ArroyoLabs/erdiko-wordpress#8]
I am trying to setup the erdiko, I followed
1. composer create erdiko/erdiko [my-project-name]
2. Added routes.
3. Third one is for copying the default themes which are not there so I run "composer require erdiko/wordpress".
4. But still the "vendor/erdiko/wordpress/public/themes/" is missing.

Seems the steps are not properly mentioned in README or am I missing something?

**Comment by arroyo** [comment]
Hi Gaurav, there's a missing folder path in the readme.  I just updated it.  

the path should be vendor/erdiko/wordpress/public/default/themes/.  A later version of erdiko added a context folder (e.g. default) but the readme unfortunately was not updated.

https://github.com/ArroyoLabs/erdiko-wordpress/tree/master/public/default/themes/clean-blog
